version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: budzilla
      MONGO_INITDB_ROOT_PASSWORD: budzilla
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
      - mongodb_data_container:/data/db

  # Database Manager
  mongo-express:
    image: mongo-express
    ports:
      - 8099:8081
    depends_on:
      - mongodb_container
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: budzilla2
      ME_CONFIG_BASICAUTH_PASSWORD: budzilla
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: budzilla
      ME_CONFIG_MONGODB_ADMINPASSWORD: budzilla
    links:
      - mongodb_container

volumes:
  mongodb_data_container:
