version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=$BUDZILLA_USER
      - POSTGRES_PASSWORD=$BUDZILLA_PASSWORD
    ports:
      - '6969:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
