version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=$BUDZILLA_USER
      - POSTGRES_PASSWORD=$BUDZILLA_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
  web:
    image: 628406611447.dkr.ecr.eu-north-1.amazonaws.com/budzilla:latest
    ports:
      - "16969:16969"
    environment:
      - SPRING_DATASOURCE_USERNAME=$BUDZILLA_USER
      - SPRING_DATASOURCE_PASSWORD=$BUDZILLA_PASSWORD
      - SERVER_PORT=$BUDZILLA_SERVER_PORT
      - spring.datasource.url=$BUDZILLA_DATASOURCE_URL
      - budzilla.jwt.secret=$BUDZILLA_JWT_SECRET
      - budzilla.jwt.expiration=$BUDZILLA_JWT_expiration
    links:
      - "db:database"
    depends_on:
      - db

volumes:
  db:
    driver: local
